queries = [
    "how is confidential data defined?",
    "how is confidential data fined in texas labor code?",
    "What qualifies as confidential data?",
    "How is confidential information defined?",
    "What constitutes confidential data?",
    "How do laws define confidential data?",
    "What is considered confidential information under data protection laws?",
    "Texas Labor Code and Confidential Data:",
    "How does the Texas Labor Code define confidential data?",
    "What is classified as confidential information in Texas labor law?",
    "How is confidential employee data handled under Texas labor laws?",
    "What are the confidentiality rules in the Texas Labor Code?",
    "What does the Texas Labor Code say about protecting confidential information?",
    "What constitutes confidential data?",
    "How do we define confidential data?",
    "What qualifies as confidential data?",
    "What is the definition of confidential data?",
    "How is sensitive information classified as confidential?",
    "What criteria determine whether data is confidential?",
    "What factors define confidential data?",
    "In what ways is data considered confidential?",
    "How is confidentiality of data determined?",
    "What makes data confidential?",
    "How do we categorize confidential information?",
    "What standards are used to define confidential data?",
    "What characteristics classify data as confidential?",
    "How is the confidentiality of information established?",
    "What guidelines determine if data is confidential?",
    "What attributes are necessary for data to be confidential?",
    "How does an organization define confidential information?",
    "What legal or organizational rules define confidential data?",
    "Under what conditions is data labeled as confidential?",
    "How do policies dictate what is considered confidential data?"
]