DROP DATABASE IF EXISTS texas_law;
CREATE DATABASE texas_law;

\c texas_law;

CREATE TYPE PROCESS_STATE AS ENUM ('NONE', 'FAILED', 'SUCCESS');

CREATE TABLE urls (
  json_metadata TEXT NOT NULL,
  url TEXT NOT NULL PRIMARY KEY,
  http_status_code INTEGER DEFAULT 0,
  response TEXT DEFAULT '',
  process_state PROCESS_STATE DEFAULT 'NONE',
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX index_urls_url ON urls (url);
